class AppConstants {
  static const String appName = 'PureCuts';
  static const String appTagline = 'Pro Salon Products, Fast Delivery';
  static const String logoPath = 'assets/icons/purecutslogo-removebg-preview.png';

  // Dummy categories
  static const List<Map<String, dynamic>> categories = [
    {'name': 'Hair Care', 'icon': 'assets/icons/hair-cutting.png'},
    {'name': 'Skin Care', 'icon': 'assets/icons/skincare.png'},
    {'name': 'Color', 'icon': 'assets/icons/hair-dye.png'},
    {'name': 'Tools', 'icon': 'assets/icons/makeup-brushes.png'},
    {'name': 'Nail', 'icon': 'assets/icons/makeup-brushes.png'},
    {'name': 'Beard', 'icon': 'assets/icons/hair-cutting.png'},
    {'name': 'Wax', 'icon': 'assets/icons/skincare.png'},
    {'name': 'Offers', 'icon': 'assets/icons/hair-dye.png'},
  ];

  // Dummy products
  static final List<Map<String, dynamic>> products = [
    {
      'id': '1',
      'name': 'L\'Oreal Professional Paris Majirel Hair Color Tube – Natural Black',
      'brand': 'L\'Oreal Professional',
      'category': 'Color',
      'price': 285,
      'originalPrice': 350,
      'rating': 4.6,
      'reviews': 342,
      'image': 'assets/products/Loreal Professional Paris Majirel Hair Color Tube – Natural Black (1 No.).png',
      'tag': 'Bestseller',
      'size': '50 ml',
      'deliveryTime': '18 MINS',
    },
    {
      'id': '2',
      'name': 'L\'Oreal Professionnel Vitamino Color Shampoo for Color Protection',
      'brand': 'L\'Oreal Professional',
      'category': 'Hair Care',
      'price': 890,
      'originalPrice': 1150,
      'rating': 4.7,
      'reviews': 256,
      'image': 'assets/products/Loreal Professionnel Vitamino Color Shampoo for Color Protection With Resveratrol (300ml).png',
      'tag': 'Top Rated',
      'size': '300 ml',
      'deliveryTime': '15 MINS',
    },
    {
      'id': '3',
      'name': 'L\'Oreal Professionnel Absolut Repair Mask',
      'brand': 'L\'Oreal Professional',
      'category': 'Hair Care',
      'price': 1420,
      'originalPrice': 1750,
      'rating': 4.8,
      'reviews': 428,
      'image': 'assets/products/Loreal Professionnel Absolut Repair Mask (250gm).png',
      'tag': 'Premium',
      'size': '250 gm',
      'deliveryTime': '15 MINS',
    },
    {
      'id': '4',
      'name': 'L\'Oreal Professionnel Xtenso Care Shampoo',
      'brand': 'L\'Oreal Professional',
      'category': 'Hair Care',
      'price': 820,
      'originalPrice': 1050,
      'rating': 4.5,
      'reviews': 187,
      'image': 'assets/products/Loreal Professionnel Xtenso Care Shampoo.png',
      'tag': '',
      'size': '300 ml',
      'deliveryTime': '18 MINS',
    },
    {
      'id': '5',
      'name': 'L\'Oreal Professionnel Xtenso Care Sulfate-free Masque',
      'brand': 'L\'Oreal Professional',
      'category': 'Hair Care',
      'price': 1250,
      'originalPrice': 1580,
      'rating': 4.6,
      'reviews': 215,
      'image': 'assets/products/Loreal Professionnel Xtenso Care Sulfate-free Masque.png',
      'tag': 'Pro Pick',
      'size': '196 gm',
      'deliveryTime': '18 MINS',
    },
    {
      'id': '6',
      'name': 'L\'Oreal Professionnel Paris Xtenso Care Leave-In Serum',
      'brand': 'L\'Oreal Professional',
      'category': 'Hair Care',
      'price': 980,
      'originalPrice': 1200,
      'rating': 4.7,
      'reviews': 294,
      'image': 'assets/products/Loreal Professionnel Paris Xtenso Care Leave-In Serum (50ml).png',
      'tag': 'Top Rated',
      'size': '50 ml',
      'deliveryTime': '15 MINS',
    },
    {
      'id': '7',
      'name': 'Matrix Professional Liquid Protein Conditioner',
      'brand': 'Matrix',
      'category': 'Hair Care',
      'price': 625,
      'originalPrice': 780,
      'rating': 4.4,
      'reviews': 168,
      'image': 'assets/products/Matrix Professional Liquid Protein Conditioner.png',
      'tag': 'New',
      'size': '400 ml',
      'deliveryTime': '20 MINS',
    },
    {
      'id': '8',
      'name': 'Garnier Color Naturals – Burgundy',
      'brand': 'Garnier',
      'category': 'Color',
      'price': 165,
      'originalPrice': 210,
      'rating': 4.2,
      'reviews': 521,
      'image': 'assets/products/Garnier Color Naturals – Burgundy (3.16 No.).png',
      'tag': 'Deal',
      'size': '3.16',
      'deliveryTime': '18 MINS',
    },
    {
      'id': '9',
      'name': 'Floractive Professional Marroco Golden Conditioner',
      'brand': 'Floractive',
      'category': 'Hair Care',
      'price': 740,
      'originalPrice': 920,
      'rating': 4.5,
      'reviews': 142,
      'image': 'assets/products/Floractive Professional Marroco Golden Conditioner-250ml.png',
      'tag': '',
      'size': '250 ml',
      'deliveryTime': '18 MINS',
    },
    {
      'id': '10',
      'name': 'L\'Oreal Professional Hair Spa – Repair',
      'brand': 'L\'Oreal Professional',
      'category': 'Hair Care',
      'price': 1580,
      'originalPrice': 1950,
      'rating': 4.8,
      'reviews': 387,
      'image': 'assets/products/Loreal Professional Hair Spa – Repair.png',
      'tag': 'Premium',
      'size': '500 ml',
      'deliveryTime': '15 MINS',
    },
    {
      'id': '11',
      'name': 'Streax Professional Argan Secret Hair Colourant Developer',
      'brand': 'Streax',
      'category': 'Color',
      'price': 185,
      'originalPrice': 240,
      'rating': 4.3,
      'reviews': 276,
      'image': 'assets/products/Streax Professional Argan Secret Hair Colourant Developer (20 Vol)- 250ml.png',
      'tag': '',
      'size': '250 ml',
      'deliveryTime': '20 MINS',
    },
  ];

  // Dummy orders
  static const List<Map<String, dynamic>> orders = [
    {
      'id': 'ORD-1001',
      'date': '5 Mar 2026',
      'items': 3,
      'total': 2450,
      'status': 'Delivered',
    },
    {
      'id': 'ORD-998',
      'date': '28 Feb 2026',
      'items': 1,
      'total': 850,
      'status': 'Delivered',
    },
    {
      'id': 'ORD-982',
      'date': '20 Feb 2026',
      'items': 5,
      'total': 6100,
      'status': 'Delivered',
    },
  ];
}
